spring.main.allow-bean-definition-overriding=true
server.port=8088
spring.application.name=demo-rest

# ????????? ????-???????????? DataSource
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Swagger ?????????
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.persistAuthorization=true
springdoc.model-converters.pageable-converter.enabled=false

# DGS GraphQL ?????????
dgs.graphql.path=/graphql
dgs.graphql.graphiql.enabled=true
dgs.graphql.graphiql.path=/graphiql
dgs.graphql.schema-locations=classpath:schema/*.graphqls
# ???????????
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.netflix.graphql.dgs=DEBUG