
spring.main.allow-bean-definition-overriding=true
server.port=8088

# ????????? DataSource
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Swagger ????????????
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Swagger UI ?????????
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.syntaxHighlight.enabled=true
springdoc.swagger-ui.persistAuthorization=true

# ??????????? ??? ???????
logging.level.org.springdoc=DEBUG