spring.main.allow-bean-definition-overriding=true
server.port=8088

# ????????? ????-???????????? DataSource
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Swagger ?????????
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.persistAuthorization=true

# ????????? ?????????????? ??????????? Pageable ??????????
springdoc.model-converters.pageable-converter.enabled=false

# ???? ?????????, ??? ?? ????? ????????? ????????? ????????? ?????????????
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

# ???????????
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
